version: '2'
services:

  squid-deb-proxy:
    build: .
    volumes:
      - ./volumes/data:/data
    ports:
      - "0.0.0.0:3142:8000"
    environment:
      - USE_ACL=${DOCKER_SQUID_USE_ACL}
      - USE_AVAHI=${DOCKER_SQUID_USE_AVAHI}
    restart: always
